trigger:
- main

pr:
- main

pool:
  vmImage: ubuntu-latest

variables:
  PRISMA_API_URL: https://api4.prismacloud.io

jobs:
- job: Prisma_Cloud_Job
  displayName: Prisma Cloud Job
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: 3.8
    displayName: 'Use Python 3.8'
  - script: pip install checkov
    displayName: Install Checkov
  - script: checkov -d . --use-enforcement-rules --bc-api-key dd516dc8-59b4-412a-92ab-7766dbb033b0::BXtATEBSqCGMOfJGhzz9Va5ZLPA= --repo-id hacksawduggan/PaloPatADO --branch master -o cli -o junitxml --output-file-path console,CheckovReport.xml
    workingDirectory: $(System.DefaultWorkingDirectory)
    displayName: Run Checkov
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/CheckovReport.xml'
      testRunTitle: PrismaCloudTests
    displayName: Publish Test Results
    condition: always()
  - task: DockerCompose@0
    inputs:
      containerregistrytype: 'Azure Container Registry'
      azureSubscription: 'Subscription 1(def352ee-0072-4ad3-afab-fa9366cc527d)'
      azureContainerRegistry: '{"loginServer":"palopatregistry.azurecr.io", "id" : "/subscriptions/def352ee-0072-4ad3-afab-fa9366cc527d/resourceGroups/Palo/providers/Microsoft.ContainerRegistry/registries/PaloPatRegistry"}'
      dockerComposeFile: '**/docker-compose.yml'
      action: 'Build services'